DROP TABLE IF EXISTS EMAILS,PETS,USERS;

CREATE  TABLE EMAILS(
 ID INT AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR (255)
 );
 CREATE TABLE PETS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NICKNAME VARCHAR (255)
);

CREATE TABLE USERS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR (255),
EMAIL_ID INT REFERENCES EMAILS(ID),
PET_ID INT REFERENCES PETS(ID)
);

